name: Auto Update Coinplex Monitor

on:
  schedule:
    - cron: '0 * * * *'  # co godzinę
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install matplotlib

      - name: Run update script
        run: python generate.py

      - name: Commit and push changes
        run: |
          git config --global user.name "limakcoinplex-bot"
          git config --global user.email "limaklee@users.noreply.github.com"
          git add index.html
          git commit -m "Automatyczna aktualizacja monitora Coinplex"
          git push
